/* Progressive controls for HTML generated by Luastra. No VM or hydration. */
(() => {
  // This blocking head script selects the closed layout before the body is painted.
  const root = document.documentElement;
  root.classList.add("docs-enhanced");
  const themeKey = "luastra.dev.luastra.sdk-reference.docs-theme";
  let theme = "light";
  try { if (localStorage.getItem(themeKey) === "v1:dark") theme = "dark"; } catch {}
  document.documentElement.dataset.docsTheme = theme;
  const ready = () => {
    const byId = id => document.getElementById(id);
    const themeButton = byId("docs/header/theme"), menu = byId("docs/header/menu");
    const sidebar = byId("docs/sidebar"), scrim = byId("docs/navigation-scrim");
    let exampleFrame;
    const syncExampleTheme = () => {
      if (!exampleFrame) return;
      const style = getComputedStyle(byId("docs/root"));
      const names = ["bg", "text", "accent", "accent-text", "accent-strong", "on-accent", "muted", "surface", "surface-raised", "success", "highlight", "danger", "border"];
      const colors = Object.fromEntries(names.map(name => [`--luastra-color-${name}`, style.getPropertyValue(`--luastra-color-${name}`).trim()]).filter(([, value]) => value));
      exampleFrame.contentWindow.postMessage({ type: "luastra-example-theme", colors }, location.origin);
    };
    const updateTheme = () => {
      root.dataset.docsTheme = theme;
      themeButton.textContent = theme === "dark" ? "☀" : "◐";
      themeButton.setAttribute("aria-label", theme === "dark" ? "Use light theme" : "Use dark theme");
      themeButton.setAttribute("aria-pressed", String(theme === "dark"));
      syncExampleTheme();
    };
    updateTheme(); themeButton.disabled = false;
    themeButton.addEventListener("click", () => { theme = theme === "dark" ? "light" : "dark"; updateTheme(); try { localStorage.setItem(themeKey, `v1:${theme}`); } catch {} });
    let menuOpen = false;
    const mobile = matchMedia("(max-width: 980px)");
    const setMenu = open => {
      menuOpen = open;
      sidebar.classList.toggle("luastra-site-sidebar-open", open);
      scrim.classList.toggle("luastra-site-scrim-open", open);
      sidebar.inert = mobile.matches && !open;
      menu.setAttribute("aria-expanded", String(open));
      menu.setAttribute("aria-label", open ? "Close navigation" : "Open navigation");
    };
    menu.disabled = false; menu.setAttribute("aria-controls", "docs/sidebar");
    menu.addEventListener("click", () => { root.classList.add("docs-menu-animated"); setMenu(!menuOpen); });
    scrim.addEventListener("click", () => { setMenu(false); menu.focus(); });
    document.addEventListener("keydown", event => { if (event.key === "Escape" && menuOpen) { setMenu(false); menu.focus(); } });
    mobile.addEventListener("change", () => { root.classList.remove("docs-menu-animated"); setMenu(false); });
    setMenu(false);
    const runExample = byId("docs/example/run");
    if (runExample) {
      const status = byId("docs/example/status");
      let timeout;
      runExample.disabled = false;
      runExample.addEventListener("click", () => {
        exampleFrame?.remove();
        exampleFrame = document.createElement("iframe");
        exampleFrame.className = "docs-example-frame";
        exampleFrame.title = "Interactive Luastra example";
        exampleFrame.style.visibility = "hidden";
        exampleFrame.src = runExample.getAttribute("data-docs-example");
        runExample.parentElement.after(exampleFrame);
        runExample.disabled = true; status.textContent = "Loading Luastra…";
        clearTimeout(timeout);
        timeout = setTimeout(() => { status.textContent = "The example could not start. Try again."; runExample.disabled = false; runExample.textContent = "Retry example"; }, 20000);
      });
      addEventListener("message", event => {
        if (!exampleFrame || event.source !== exampleFrame.contentWindow || event.origin !== location.origin || event.data?.type !== "luastra-example-ready") return;
        const height = event.data.height;
        if (!Number.isFinite(height) || height <= 0) return;
        clearTimeout(timeout);
        exampleFrame.style.visibility = "visible";
        exampleFrame.height = String(Math.min(2000, Math.max(160, height)));
        exampleFrame.style.height = `${Math.min(2000, Math.max(160, height))}px`;
        runExample.parentElement.hidden = true;
        syncExampleTheme();
      });
    }
    sidebar.addEventListener("click", event => {
      const link = event.target.closest("a[href]");
      if (!menuOpen || !mobile.matches || !link || event.defaultPrevented || event.button !== 0 || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey || link.hasAttribute("download") || (link.target && link.target !== "_self")) return;
      setMenu(false);
      if (matchMedia("(prefers-reduced-motion: reduce)").matches) return;
      event.preventDefault();
      // Animate the outgoing menu, never the initial state of the destination page.
      const destination = link.href;
      let timer;
      const navigate = () => {
        clearTimeout(timer);
        sidebar.removeEventListener("transitionend", finished);
        location.assign(destination);
      };
      const finished = event => { if (event.target === sidebar && event.propertyName === "transform") navigate(); };
      sidebar.addEventListener("transitionend", finished);
      timer = setTimeout(navigate, 220);
    });
    const copy = document.querySelector("[data-docs-copy]");
    if (copy) {
      copy.disabled = false;
      const status = document.createElement("p"); status.className = "luastra-text"; status.setAttribute("role", "status"); status.hidden = true; copy.after(status);
      copy.addEventListener("click", async () => {
        const source = byId("docs-copy-source");
        const text = source.content.textContent;
        status.hidden = false;
        try { await navigator.clipboard.writeText(text); status.textContent = "Example copied."; }
        catch { status.textContent = "Could not copy the example. Select the code and copy it manually."; }
      });
    }
    const search = byId("docs/search"), content = byId("docs/content");
    const originals = [...content.children];
    const results = document.createElement("section"); results.className = "luastra-column luastra-gap-sm docs-search-results"; results.hidden = true; content.append(results);
    let indexPromise;
    const load = () => indexPromise ??= fetch("/docs/search-index.json").then(r => { if (!r.ok) throw Error("Search unavailable"); return r.json(); }).catch(error => { indexPromise = null; throw error; });
    const clear = () => { search.value = ""; results.hidden = true; for (const node of originals) node.hidden = false; search.focus(); };
    let revision = 0;
    search.disabled = false;
    search.addEventListener("input", async () => {
      const current = ++revision, needle = search.value.slice(0, 160).trim().toLowerCase();
      if (!needle) { clear(); return; }
      for (const node of originals) node.hidden = true;
      results.hidden = false; results.replaceChildren();
      const count = document.createElement("h3"); count.className = "luastra-text"; count.setAttribute("role", "status"); count.textContent = "Searching…";
      const reset = document.createElement("button"); reset.className = "luastra-button"; reset.textContent = "Clear search"; reset.addEventListener("click", clear); results.append(count, reset);
      try {
        const index = await load(); if (current !== revision) return;
        const matches = index.filter(item => item.text.includes(needle));
        count.textContent = matches.length ? `Results: ${matches.length}${matches.length > 40 ? " (showing first 40)" : ""}` : "No results";
        for (const item of matches.slice(0, 40)) {
          const card = document.createElement("section"); card.className = "luastra-card luastra-site-reference-card";
          const link = document.createElement("a"); link.className = "luastra-link"; link.href = item.path; link.textContent = item.title;
          const description = document.createElement("p"); description.className = "luastra-text luastra-tone-muted"; description.textContent = item.description;
          card.append(link, description); results.append(card);
        }
      } catch { if (current === revision) count.textContent = "Search could not load. Clear search to continue reading."; }
    });
  };
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", ready, { once: true }); else ready();
})();
